name: Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun test